schema_version = "1.0.0"
id = "NodeMemo"
version = "1.0.0"
name = "节点随记"
tagline = "为节点思路设置清晰的路标和精准的导航"
maintainer = "無東"
type = "add-on"
permissions = []
tags = ["Node"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]